# This is a basic workflow to help you get started with Actions

name: Emailer-demo

on:
  push:
    branches:
      - master
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "email"
  email:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#    Checkout will be required if need to load local htmnl file and attachment. Uncomment html_body,content_type and convert_markdown true
#      - name: Checkout code
#        uses: actions/checkout@v2
      - name: ✨ Send email, you star
        uses: rajsh018/email-bot@v1.0
        with:
          server_address: ${{secrets.MAIL_SERVER}} #smtp.gmail.com
          server_port: ${{secrets.MAIL_PORT}} #465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: New Update from SDK Version ${{ env.RELEASE_VERSION }}
          body: ${{ github.actor }} just starred your mail-on-star repo!!! ${{ github.repository }}
#          html_body: "file://demo-page.html" #Just launched new version of my ${{github.repository}}
#          content_type: text/html
#          convert_markdown: true
          to: ${{secrets.USER_EMAILS}}
          from: Rajan Shukla
